baseURL = 'https://www.cabinet-dr-bancescu.ro/'
languageCode = 'en-us'
title = 'Avancris - Întelegem Mintea, Susținem Omul'
theme = 'hugo-profile'

[params]
  title = "Avancris"
  description = "Avancris - Întelegem Mintea, Susținem Omul"
  # staticPath = ""  # The path to serve the static files from
  # favicon = "/doctor-office/"
  # Whether the fade animations on the home page will be enabled
  animate = true

[markup.goldmark.renderer]
  unsafe = true

  [params.font]
    fontSize = "1rem" # default: 1rem
    fontWeight = 400 # default: 400
    lineHeight = 1.5 # default: 1.5
    textAlign = "left" # default: left

  # If you want to customize the menu, you can change it here
  [params.navbar]
    align = "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo = "./fav.png" # Logo for the brand | default is the favicon variable
    showBrandLogo = true # Show brand logo in nav bar | default is true
    brandName = "Avancris" # Brand name for the brand | default is the title variable
    disableSearch = true
    # searchPlaceholder = "Search"
    enableSeparator = false

    [params.navbar.stickyNavBar]
      enable = true
      showOnScrollUp = true

    [params.navbar.menus]
      disableAbout = false
      disableExperience = false
      disableEducation = false
      disableProjects = false
      disableAchievements = false
      disableContact = false

  # Hero
  [params.hero]
    enable = true
    intro = "Bine ați venit la"
    title = "AVANCRIS"
    subtitle = "Empatie - Echilibru - Evoluție"
    content = "La S.C. AVANCRIS S.R.L. oferim servicii medicale specializate dedicate evaluării pacienților, diagnosticării acestora și tratamentului tulburărilor psihice, într-un cadru sigur, discret și empatic."
    image = "./logo.jpeg"

    [params.hero.bottomImage]
      enable = true
      roundImage = false # Make hero image circular | default false

    [params.hero.button]
      enable = false
      name = "Resume"
      url = "#"
      download = true
      newPage = false


# About
  [params.about]
    enable = true
    title = "Echipa noastră"
    image = "./avancris-team.png"
    content = """
Echipa noastră, formată din medic, psiholog, asistent medical oferă o abordare integrată a sănătății mintale, cu accent pe respect și echilibrarea psihică a pacientului.
"""
    [params.about.skills]
      enable = false
      title = "Servicii oferite:"
      items = [
        
      ]

  # About
  [params.about2]
    enable = true
    title = "Dr. Băncescu Răzvan-Alexandru - Parcurs de excepție"
    image = "./hero.jpeg"
    content = """
La începutul anilor ‘90, în cadrul Colegiul Național I.C. Brătianu Pitești, continuat cu Universitatea de Medicină și Farmacie ”Tg. Mureș” și ulterior rezidențiatul efectuat într-un cadru totalmente profesionist la Spitalul Clinic de Urgență Militar Central ,,Carol Davila’’ –  Bucuresti, sub îndrumarea Conf. univ. dr. col. Vasiliu Octavian.


Continuă ulterior cu o experiență de peste 16 ani în Spitalul Județean de Urgență Pitești, Sectia Psihiatrie (în perioada martie 2024 - decembrie 2025 Medic Șef  Secție), în paralel în perioada 2015-2026 membru al Comisiei Medico-Legale Psihiatrice în cadrul Serviciului de Medicină Legală Argeș.
"""
    [params.about2.skills]
      enable = true
      title = "Servicii oferite:"
      items = [
        "Consultații (inclusiv la domiciliu) cu diagnosticare",
        "Eliberare de rețete simple/compensate, scrisori medicale, scheme de tratament, bilete de trimitere",
        "Evaluări psihiatrice complexe",
        "Eliberare de referate medicale(necesare la CECM, DGASPC – Handicap)",
        "Completare program recuperator",
        "Eliberare de adeverințe medicale",
        "Eliberare raport de evaluare psihiatrică pentru instanța(tutela)"
      ]

  # Second About Section (Custom Added)
  [params.about3]
    enable = true
    title = "Psiholog - Lungan Cristina Elena"
    image = "./logo.jpeg"
    content = """
Cu o experiență de peste 10 ani în domeniul psihologiei și psiho-pedagogiei, oferă suport specializat în evaluarea și consilierea pacienților, contribuind la menținerea și îmbunătățirea echilibrului emoțional.
"""
    [params.about3.skills]
      enable = true
      title = "Servicii oferite:"
      items = [
        "Testări clinice(PANSS, YMRS, HAM-D, HAM-A, MMSE, TEST CEAS, GAFS, etc.) cu rapoarte de evaluare psihologică",
        "Consiliere psihologică",
        "Terapii (de suport imediat, cognitiv-comportamentală, psihodinamică/psihanalitică, centrată pe persoană, de cuplu și familie, prin expunere)",
        "Eliberare avize psihologice (psihologie clinică, psihologia muncii, psihologia transporturilor)",
        "Eliberare raport de evaluare psihologică pentru instanță (tutelă)"
      ]


  # Third About Section (Custom Added)
  [params.about4]
    enable = true
    title = "Asistent medical - Catrina Maria Denisa"
    image = "./logo.jpeg"
    content = """
Cu  experiență de peste 12 ani în domeniul psihiatriei de ambulatoriu și al îngrijirii medico-psihiatrice, asigură suport medical și contribuie la monitorizarea și îngrijirea pacienților.
"""
    [params.about4.skills]
      enable = false
      title = "Competențe:"
      items = [
        "Specialitate 1",
        "Specialitate 2"
      ]


  # Education
  [params.education]
    enable = true
    title = "Prețuri"
    index = false

    [[params.education.items]]
      title = "Listă prețuri psihiatrie"
      content = """
<style> table { width: 100%; } </style>

| Serviciu | Preț |
| :--- | ---: |
| Consultație pacient nou/neprogramată/în regim de urgență | **350 lei** |
| Consultație control | **250 lei** |
| Consultație cu B.T. | **–** |
| Eliberare referat medical pentru CECM cu completare program recuperator (pacienți dispensarizați) | **250 lei** |
| Eliberare referat medical pentru Comisia de Handicap – DGASPC (pacienți dispensarizați) | **250 lei** |
| Eliberare referate medicale (CECM, Handicap) pentru pacienții nedispensarizați | **300 lei** |
| Eliberare adeverințe medicale | **150 lei** |
| Examinare pentru certificat prenupțial (2 pers.) | **200 lei** |
| Eliberare copie după fișa de dispensarizare | **150 lei** |
| Consultație la domiciliu (programare prealabilă, max. 5 km. de Pitești) | **500 lei** |
| Consultație la domiciliu (programare prealabilă, max. 25 km. de Pitești) | **750 lei** |
| Raport de evaluare psihiatrică pentru instanță (tutelă) | **1.000 lei** |
| Raport de evaluare psihiatrică pentru instanță (tutelă) la domiciliu | **1.300 lei** |
  """


    [[params.education.items]]
      title = "Listă prețuri psihologie"
      content = """

| Serviciu | Preț |
| :--- | ---: |
| Rapoarte de evaluare psihologică cu testări pentru CECM, DGASPC (Handicap) | **200 lei** |
| Consiliere psihologică (45 - 50 min.) | **200 lei** |
| Consiliere psihologică suportivă, în regim de urgență (30 min.) | **150 lei** |
| Psihoterapii (50 - 60 min.) | **300 lei/ședință** |
| Eliberare avize pentru psihologie clinică, psihologia muncii, psihologia transporturilor | **150 lei** |
| Examinare psihologică (testări, consiliere psihologică, psihoterapie de scurtă durată) la domiciliu (programare prealabilă, max. 5 km. de Pitești) | **350 lei** |
| Examinare psihologică (testări, consiliere psihologică, psihoterapie de scurtă durată) la domiciliu (programare prealabilă, max. 25 km. de Pitești) | **500 lei** |
| Raport de evaluare psihologică pentru instanță (tutelă) | **600 lei** |
| Raport de evaluare psihologică pentru instanță (tutelă) la domiciliu | **800 lei** |
  """

  

  #Contact
  [params.contact]
    enable = true
    title = "Contactează-ne"
    content = """
    Ne găsiți la adresa: Pitești, Cartier Eremia Grigorescu, Str. Trandafirilor, Bl. P2.
    Pentru programări:
        Telefon: 0730 388 176 
        Luni - Vineri: 09:00 - 15:00 
    """


  # List pages like blogs and posts
  [params.listPages]
    disableFeaturedImage = false

  # Single pages like blog and post
  [params.singlePages]
    socialShare = true

    [params.singlePages.readTime]
      enable = true
      content = "min read"

    [params.singlePages.scrollprogress]
      enable = true

    [params.singlePages.tags]
      openInNewTab = true

  # For translations
  [params.terms]
    read = "Read"
    toc = "Table Of Contents"
    copyright = "All rights reserved"
    emailText = "Check out this site"

  [params.datesFormat]
    article = "Jan 2, 2006"
    articleList = "Jan 2, 2006"
    articleRecent = "Jan 2, 2006"

  #customScripts = """ # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
  #"""